### GENERAL SETTINGS ###

# Site settings
title: Engineering Mentorship 101
description: "Online Portfolio for UC San Diego Fall 2014 CAT 125 course."
analytics: UA-50546869-2
baseurl: "/engmentor101" #important: start with /
url: "http://xueyj.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" (Color of the area under the title bar/section)
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D" (Color of the header/title bar where the Section links are located)
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3" # (Color of footer text)

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 9450 Gilman Drive
    - La Jolla, CA
Email: dixu@ucsd.edu
Phone: (626) xxx-xxxx

about: "Engineering Mentorship 101 is a free website to provide to you, useful content. Copyright Erik Xu."